/* 
* This class is used as a wrapper class to store the data getting from response and showing sending it in UI
*/
public class EventShowWrapper {
    public String eventName;
    public String description;
    public String startTime;
    public String endTime;
    public String url;
    public String status;
    public String currencys;
    public String summary;
    public String venue_id;
    public String organization_id;
    public String eventId;
    public String apiResponse;
    public String apiEndpointURL;
    public String apiMethod;
    public String apiStatusCode;
    public String apiRequest;
    public String userId;
    public String userName;
    
}