/* 
* This class is used as a wrapper class to store the data input by user and convert it into object and creat a request.
*/
public class EventInputWrapper{
      public String eventName; //ABC
      public String eventDescription; //ABC
      public String startDateTime; //2018-05-12T02:00:00Z
      public String endDateTime; //2018-05-13T02:00:00Z
      public String password; //Hellofine28@
      public Integer capacity;    //10
      public Boolean eventSeatMapValue;
      public Boolean eventSeatValue;
      public Boolean eventSeriesValue;
      public Boolean eventSelectSeatValue;
      public String currencys; //USD
      public String locale; //de_AT
      public Boolean eventOnlineValue;
     public Boolean eventListedValue;
    public String organizerId;
      public Boolean eventShareableValue;
      public Boolean eventInviteValue;
      public Boolean eventRemaningValue;
      public Boolean eventColorValue;
      public String timeZone; //UTC

}
