public class EventWrapper{
 public String id; //12345
 public cls_name name;
 public cls_description description;
 public cls_start start;
 public cls_end ends;
     public String summary;
     public String venue_id; //80535429
 public String url; //https://www.eventbrite.com/e/45263283700
 public String vanity_url; //https://testevent.eventbrite.com
 public String created; //2017-02-19T20:28:14Z
 public String changed; //2017-02-19T20:28:14Z
 public String published; //2017-02-19T20:28:14Z
 public String status; //live
 public String currencys; //USD
 public Boolean online_event;
 public String organization_id; //
 public String organizer_id; //
 public cls_organizer organizer;
 public Integer logo_id;
 public cls_logo logo;
 public cls_venue venue;
 
}
